name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download dependencies
      run: |
        dir=.m2/repository/com/github/desyncr/freenet-node-metrics/0.3
        mkdir -p $dir
        wget https://github.com/AHOHNMYC/freenet-node-metrics/releases/download/0.3/node-metrics-0.3.jar -qO $dir/freenet-node-metrics-0.3.jar

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: jar

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: build/*
        name: "freenet-NodeMetrics"
